name: Build & Test (Fullstack)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo root files
        run: ls -la

      # --- Backend (.NET) ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore backend dependencies
        run: dotnet restore ExplorationApi.csproj

      - name: Build backend
        run: dotnet build ExplorationApi.csproj --no-restore --configuration Release

      - name: Run backend tests
        run: dotnet test u ExplorationApi.csproj --no-build --configuration Release
      
      - name: Show ExplorationApi contents
        run: ls -la ExplorationApi

      # --- Frontend (Angular) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd homepage
          npm install

      - name: Build frontend
        run: |
          cd homepage
          npm run build

      - name: Show ExplorationApi contents
        run: ls -la ExplorationApi
